### ISSUE TITLE
Support Genesis Config?

### ISSUE THREAD

**Issue by seunlanlege** [kurtosis-tech/eth-network-package#111]
Would be useful if the config also supported specifying a custom genesis config, this would allow specifying prefunded accounts and predeployed contracts like the create2 deployer.

eg https://github.com/OffchainLabs/eth-pos-devnet/blob/master/execution/genesis.json

**Comment by leeederek** [comment]
Hi @seunlanlege, thanks for submitting a Github issue. We took a look and have assessed that the work is not trivial to enable the eth2-package or the eth-network-package to take in arbitrary/custom genesis config files. 

Do you mind sharing some more details on how you would use the eth2-package or eth-network-package if you could specify certain prefunded accounts and predeployed contracts? 

We would also welcome contributions from the community, so let us know if you need help with making this change yourself!
