### ISSUE TITLE
Replace `time.now()` with `run_sh` or `run_python`

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/eth-network-package#114]
There is a `time.now()` call here: https://github.com/kurtosis-tech/eth-network-package/blob/30d2ccf8feae4fadc859a19c4a0697f2659cc90b/src/participant_network.star#L67

This is problematic, because it blocks the entire package from being used with idempotent runs.

What we need to do: replace the in-Starlark `time.now()` generation (which is an interpretation-time value) with a runtime value by generating the current time via `run_sh` or `run_python`. Hopefully, this should be the only change needed.

**Comment by leeederek** [comment]
+1 lets prioritize this. we have a user who is doing rapid dev loops with eth2-package and the lack of idempotent runs is causing friction.
