### ISSUE TITLE
Pin EL/CL client images to working versions

### ISSUE THREAD

**Issue by tedim52** [kurtosis-tech/eth-network-package#12]
Currently, [default EL/CL client images](https://github.com/kurtosis-tech/eth-network-package/blob/4c2ccaa8af5a5d4a855b572974c15b6a49f1b81a/package_io/input_parser.star#L1) are set to pull latest versions which prevents these clients from working if something is broken upstream. Pinning them to a known working docker image version will prevent this.

```
DEFAULT_EL_IMAGES = {
	"geth": "ethereum/client-go:latest",
	"erigon": "thorax/erigon:devel",
	"nethermind": "nethermind/nethermind:latest",
	"besu": "hyperledger/besu:develop"
}

DEFAULT_CL_IMAGES = {
	"lighthouse": "sigp/lighthouse:latest",
	"teku":       "consensys/teku:latest",
	"nimbus":     "statusim/nimbus-eth2:multiarch-latest",
	"prysm":    "gcr.io/prysmaticlabs/prysm/beacon-chain:latest,gcr.io/prysmaticlabs/prysm/validator:latest",
	"lodestar": "chainsafe/lodestar:next",
}
```

**Comment by leoporoli** [comment]
@tedim52 Did you already fix this, right? Could you close this ticket if it's true
