### ISSUE TITLE
Support HTTPS connections

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/eth-network-package#15]
To connect the a local eth network to a local chainlink node, it must expose a port with HTTPS. This github issue is for adding support for HTTPS connections

**Comment by leoporoli** [comment]
@leeederek how urgent is this ticket? is any user requesting this now or can we move this to the BackBurner?

**Comment by adschwartz** [comment]
@leeederek let us know the priority on this ticket

**Comment by h4ck3rk3y** [comment]
@leeederek should we close this? Its quite dated.
