### ISSUE TITLE
Make it possible to configure taints and tolerations/node selectors on the pod level

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/eth-network-package#89]
It would be great to have a way to configure kubernetes taints/toleration or node selectors (or possibly to just add whatever labels I want) to a specific container from the a config file.

This feature would enable us to be able to speed up deployment in certain scenarios, where we could run genesis generator pod on a overpowered machine, but use normal compute nodes for the rest of the tasks.

**Comment by h4ck3rk3y** [comment]
I would probably add a related ticket to the [monorepo](https://github.com/kurtosis-tech/kurtosis) as well as this requires some product work.
